{
 "title": "Debug K8s my dguyhasnoname",
 "description": "This dashboard can help troubleshooting issue in k8s cluster at cluster, node and namespace level.",
 "tags": [
  "kubernetes",
  "k8s",
  "namespace"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(up,cluster)" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_created{cluster=\"$cluster\"},node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(kube_namespace_labels{cluster=\"$cluster\"})"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "kube_pod_container_info{cluster=\"$cluster\",namespace=\"$namespace\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "**********This k8s dashboard awesome!**********",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Overall cluster $cluster status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "$cluster cluster  node current status",
     "type": "btplc-status-dot-panel",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
     "format": "none",
     "targets": [
      {
       "expr": "(kube_node_status_condition{cluster=\"$cluster\",status=\"true\",condition=\"Ready\"}) ",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "$cluster cluster node status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kube_node_status_condition{cluster=\"$cluster\",status=\"true\",condition=\"Ready\"}) ",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Namespaces",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": " count(count by (namespace)(container_spec_memory_reservation_limit_bytes{cluster=\"$cluster\",pod!=\"\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 9, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=\"$cluster\",pod!=\"\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Waiting pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_pod_container_status_waiting{cluster=\"$cluster\"} !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Terminated pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_pod_container_status_terminated_reason{cluster=\"$cluster\",reason!=\"Completed\"} !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "OOMKilled pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 17, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_pod_container_status_terminated_reason{cluster=\"$cluster\",reason=\"OOMKilled\"} != 0 ) or vector(0)"
      }
     ]
    },
    {
     "title": "$cluster cluster etcd object count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(etcd_object_counts{cluster=\"$cluster\"}) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "PVCs",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_persistentvolumeclaim_info{cluster=\"$cluster\"}) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ReadOnly PVC",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_pod_spec_volumes_persistentvolumeclaims_readonly{cluster=\"$cluster\"} != 0) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Besteffort  pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=\"$cluster\",id=~\"/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-.*\",id!~\".*.scope\",pod!=\"\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "burstable  pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=\"$cluster\",id=~\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-.*\",id!~\".*.scope\",pod!=\"\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Deployments ",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 17, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_deployment_created{cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Deployments in last 24h",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(time() -(kube_deployment_created{cluster=\"$cluster\"}) < 86400) or vector(0)"
      }
     ]
    },
    {
     "title": "Node  wise load in $cluster cluster",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load5{cluster=\"$cluster\"} + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\"}",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory usage in $cluster cluster",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{cluster=\"$cluster\",pod!=\"POD\",namespace!=\"\"})",
       "legendFormat": "Total memory used in $cluster"
      },
      {
       "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\",resource=\"memory\"})",
       "legendFormat": "Total memory in $cluster"
      }
     ]
    },
    {
     "title": "Memory usage in $cluster cluster by node",
     "type": "graph",
     "description": "This panel shows node memory usage:\n\nnode_memory_MemTotal - node_memory_MemAvailable",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "((node_memory_MemTotal{cluster=\"$cluster\"}  + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\"}) - (node_memory_MemAvailable{cluster=\"$cluster\"}  + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\"}))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory usage by namespace in $cluster cluster",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "(sum by (namespace)(container_memory_usage_bytes{cluster=\"$cluster\",pod!=\"POD\",namespace!=\"\"}))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Overall CPU usage in $cluster cluster",
     "type": "graph",
     "description": "This panel shows node CPU utilisation",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(sum by (instance,nodename) (irate(node_cpu{cluster=\"$cluster\",mode!~\"guest.*|idle|iowait\"}[5m])) + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\"})",
       "legendFormat": "Total Used CPU in $cluster cluster"
      },
      {
       "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\",resource=\"cpu\"})",
       "legendFormat": "Total CPU in $cluster cluster"
      }
     ]
    },
    {
     "title": "Node CPU usage[5m] in $cluster cluster",
     "type": "graph",
     "description": "This panel shows node CPU utilisation",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (instance,nodename) (irate(node_cpu{cluster=\"$cluster\",mode!~\"guest.*|idle|iowait\"}[5m])) + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\"})",
       "legendFormat": "{{nodename}} "
      }
     ]
    },
    {
     "title": "Waiting/Terminated pods in $cluster cluster",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by(namespace,reason) (kube_pod_container_status_terminated_reason{cluster=\"$cluster\",reason!=\"Completed\"} !=0 )",
       "legendFormat": "TERMINATED::{{reason}}::{{namespace}}"
      },
      {
       "expr": "count by(namespace,reason) (kube_pod_container_status_waiting_reason{cluster=\"$cluster\"} !=0 )",
       "legendFormat": "WAITING::{{reason}}::{{namespace}}"
      },
      {}
     ]
    }
   ]
  },
  { "title": "$node Node details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "$node uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": " (\n (sum(time() - node_boot_time{cluster=\"$cluster\"}+ on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\",nodename=\"$node\"})) \nand \nON() kube_node_status_condition{cluster=\"$cluster\",status=\"true\",condition=\"Ready\",node=\"$node\"} == 1 \n)"
    }
   ]
  },
  {
   "title": "Node $node Ready state ",
   "type": "graph",
   "description": "This panel shows the NotReady state of nodes. If any node goes in NotReady state, graph value will go from 1 to 0.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_node_status_condition{cluster=\"$cluster\",status=\"true\",condition=\"Ready\",node=\"$node\"}) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node $node load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{cluster=\"$cluster\"} + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\",nodename=\"$node\"}",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "kube_node_status_capacity_cpu_cores{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "Memory/Disk/PID Pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_node_status_condition{cluster=\"$cluster\",status=\"true\",condition=~\"MemoryPressure|PIDPressure|DiskPressure\",node=\"$node\"})",
     "legendFormat": "{{node}}::{{condition}}"
    }
   ]
  },
  {
   "title": "pod count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=\"$cluster\",node=\"$node\",pod!=\"\"}))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "besteffort",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=\"$cluster\",id=~\"/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-.*\",id!~\".*.scope\",node=\"$node\",pod!=\"\"}))"
    }
   ]
  },
  {
   "title": "burstable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=\"$cluster\",id=~\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-.*\",id!~\".*.scope\",node=\"$node\",pod!=\"\"}))"
    }
   ]
  },
  {
   "title": "Node $node CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(irate((sum by (instance) (node_cpu{cluster=\"$cluster\",mode!~\"guest.*|idle|iowait\"}))[5m:2m]) + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\",nodename=\"$node\"})",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "kube_node_status_capacity{cluster=\"$cluster\",node=\"$node\",resource=\"cpu\"}",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "Total CPU requests on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "kube_node_status_capacity{cluster=\"$cluster\",node=\"$node\",resource=\"cpu\"}",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "Total CPU limits on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "total limits"
    },
    {
     "expr": "kube_node_status_capacity{cluster=\"$cluster\",node=\"$node\",resource=\"cpu\"}",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "$node node FS available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance,nodename,mountpoint) (node_filesystem_avail{cluster=\"$cluster\"} * on(instance) group_left(nodename) node_uname_info{cluster=\"$cluster\",nodename=\"$node\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Node $node memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal{cluster=\"$cluster\"}  + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\",nodename=\"$node\"}) - (node_memory_MemAvailable{cluster=\"$cluster\"}  + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\",nodename=\"$node\"})",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "kube_node_status_capacity{cluster=\"$cluster\",node=\"$node\",resource=\"memory\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "Total memory requests on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "kube_node_status_capacity{cluster=\"$cluster\",node=\"$node\",resource=\"memory\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "Total Memory limits on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "total mem limits "
    },
    {
     "expr": "kube_node_status_capacity{cluster=\"$cluster\",node=\"$node\",resource=\"memory\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "NTP time deviation on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,nodename)(node_timex_estimated_error_seconds{cluster=\"$cluster\"}) + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\",nodename=\"$node\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Pod count on $node by namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (namespace)(container_memory_working_set_bytes{image!=\"\",cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "{{namespace}}"
    },
    {}
   ]
  },
  {
   "title": "Top 5  memory guzzling pods on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": " sort(topk(5, container_memory_working_set_bytes{image!=\"\",cluster=\"$cluster\",node=\"$node\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "container count by pod on node $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by (pod)(container_memory_working_set_bytes{image!=\"\",cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "kubelet_runtime_operations_errors_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors_total{job=\"kubelet\",cluster=\"$cluster\",node=\"$node\"}[5m])) by (node, operation_type)",
     "legendFormat": "{{node}}: {{operation_type}}"
    }
   ]
  },
  {
   "title": "kubelet_pleg_relist_duration_seconds_bucket",
   "type": "graph",
   "description": "The PLEG health check  calls docker ps to detect container states changes, and call docker ps and inspect to get the details of those containers.\nAfter finishing each iteration, it updates a timestamp. If the timestamp hasn't been updated for a while (i.e., 3 minutes), the health check fails.\n\nUnless your node is loaded with huge number of pods that PLEG can't finish doing all these in 3 minutes (which should not happen), the most probable cause would be that docker is slow.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (node,le) (rate(kubelet_pleg_relist_duration_seconds_bucket{cluster=\"$cluster\",node=\"$node\"}[5m])))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "kubelet_eviction_stats_age_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kubelet_eviction_stats_age_seconds_sum{cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "kubelet_network_plugin_operations_duration_seconds_bucket",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (operation_type)(kubelet_network_plugin_operations_duration_seconds_bucket{cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "kubelet_network_plugin_operations_latency_microseconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (operation_type)(kubelet_network_plugin_operations_latency_microseconds{cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  { "title": "Namespace $namespace details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Pod readiness in $namespace namespace",
   "type": "btplc-status-dot-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 40 },
   "format": "none",
   "targets": [
    {
     "expr": "(kube_pod_container_status_ready{cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}::{{container}}"
    }
   ]
  },
  {
   "title": "Ready pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{cluster=\"$cluster\",namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{cluster=\"$cluster\",namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVCs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info{cluster=\"$cluster\",namespace=\"$namespace\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "pod count on nodes of $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by (node)(kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "memory  usage by pods in $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": " sort(container_memory_working_set_bytes{image!=\"\",cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated{cluster=\"$cluster\",namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_deployment_created{cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Readonly PVC",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_spec_volumes_persistentvolumeclaims_readonly{cluster=\"$cluster\",namespace=\"$namespace\"} != 0) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "memory usage by container $container in $namespace namespace",
   "type": "graph",
   "description": "container_memory_usage_bytes  includes memory usage in bytes,   including all memory regardless of when it was accessed.. The better metric is container_memory_working_set_bytes as this is what the OOM killer is watching for.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": " (container_memory_working_set_bytes{image!=\"\",cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\"})",
     "legendFormat": "{{pod}}::{{node}}"
    },
    {
     "expr": "container_memory_usage_bytes{image!=\"\",cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\"}",
     "legendFormat": "container_memory_usage_bytes for {{pod}}"
    }
   ]
  },
  {
   "title": "Waiting/Terminated pods in $namespace namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(pod,reason) (kube_pod_container_status_terminated_reason{cluster=\"$cluster\",namespace=\"$namespace\",reason!=\"Completed\"} !=0 )",
     "legendFormat": "TERMINATED::{{reason}}::{{pod}}"
    },
    {
     "expr": "count by(pod,reason) (kube_pod_container_status_waiting_reason{cluster=\"$cluster\",namespace=\"$namespace\"} !=0 )",
     "legendFormat": "WAITING::{{reason}}::{{pod}}"
    },
    {}
   ]
  },
  {
   "title": "Pod  $container node relation",
   "type": "graph",
   "description": "This panel shows no. of pod restarts in a namespace. Please choose container name from top of dashboard to check for the nodes where the pod with same container has jumped.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$container.*\"})",
     "legendFormat": " {{node}}::  {{pod}}"
    }
   ]
  },
  {
   "title": "pod restarts in $namespace namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=\"$namespace\"}[2m]) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "persistentvolumeclaim in namespace $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(kube_persistentvolumeclaim_access_mode{cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "{{access_mode}}::{{persistentvolumeclaim}}"
    },
    {
     "expr": "kube_persistentvolumeclaim_status_phase{cluster=\"$cluster\",namespace=\"$namespace\",phase=\"Bound\"}",
     "legendFormat": "Bound::{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "pod $container state in $namespace namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_pod_container_status_ready{cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\"}) ",
     "legendFormat": "READY::{{pod}}::container $container"
    },
    {
     "expr": "(kube_pod_container_status_waiting{cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\"})",
     "legendFormat": "WAITING::{{pod}}::container $container "
    },
    {
     "expr": "(kube_pod_container_status_terminated{cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\"})",
     "legendFormat": "TERMINATED::{{pod}}::container $container"
    }
   ]
  },
  {
   "title": " $namespace pods on $node",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "count by (pod)(container_memory_usage_bytes{cluster=\"$cluster\",namespace=\"$namespace\",node=\"$node\"})"
    }
   ]
  },
  {
   "title": "pods running in $namespace",
   "type": "table-old",
   "gridPos": { "h": 18, "w": 18, "x": 6, "y": 68 },
   "targets": [
    {
     "expr": "kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Resource Quota in namespace $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_resourcequota{cluster=\"$cluster\",namespace=\"$namespace\",resource=~\".*.memory.*\"}/1024^3",
     "legendFormat": "{{type}}::{{resource}} GB"
    },
    {
     "expr": "kube_resourcequota{cluster=\"$cluster\",namespace=\"$namespace\",resource=~\".*.storage.*\"}/1024^3",
     "legendFormat": "{{type}}::{{resource}} GB"
    }
   ]
  }
 ]
}